########## START OF generate_start_gcode ##########

def generate_start_gcode(gcode):

    # write in gcode to initiate a print
    
    gcode.append(";BotSlicer generated by Terek Li \n")
    gcode.append(";Optimized specifically for 3D printing via Direct Ink Writing \n")
    gcode.append("\n")
    gcode.append("\n")
    gcode.append("\n")

    gcode.append(";Initialize")
    gcode.append("M82; Absolute extrusion mode")
    gcode.append("G21; Unit to (mm)")
    gcode.append("G90; Absolute position")
    gcode.append("M82; Absolute extrusion mode")
    gcode.append("M107; Fan off")
    gcode.append('G92 E0 X0 Y0 Z0; Reset current X, Y, Z, and E axis position')
    gcode.append('G1 F50 E0.5; Prime print head')
    gcode.append('G92 E0; Reset E axis position')
    gcode.append('G92 E0; Reset E axis position')
    gcode.append('G92 E0; Reset E axis position')
    gcode.append(";End of Initiation \n")
    
    return gcode

########## END OF generate_start_gcode ##########



########## START OF generate_end_gcode ##########

def generate_end_gcode(gcode):

    # Write in gcode to end a print
    
    gcode.append(";\n")
    gcode.append("; Finished Print")
    gcode.append("G92 E2 Z0; Get ready for reverse ink extrusion")
    gcode.append("G1 E0; Retract ink to prevent dripping")
    gcode.append("G1 F1000 Z7; Quickly move up the print head away from printed object")
    gcode.append("M190 S0; Do not wait for bed temperature")
    gcode.append("M104 S0; Do not wait for hot end temperature")
    gcode.append("M107; Fan off")
    gcode.append("M84; Disable stepper motor")
    gcode.append("M82; Absolute extrusion mode")
    gcode.append(";End of GCode")

    return gcode

########## END OF generate_end_gcode ##########



########## START OF save_gcode ##########

def save_gcode(gcode, output_name):
    
    # Save GCode to local file
    
    with open(output_name, 'w') as f:
        for line in gcode:
            f.write("%s\n" % line)
            
########## END OF save_gcode ##########
